package modelo;
// Generated 2/10/2018 03:11:32 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

/**
 * Alumno generated by hbm2java
 */

@Entity
@Table(name = "Alumno")
public class Alumno  implements Serializable {


    @Id@GeneratedValue(strategy =GenerationType.IDENTITY )
    @Column(name = "idAlumno")
     private int idAlumno;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "username")
     private Usuario username;
    @OneToMany(mappedBy = "idAlumno")
     private List<Asesorar> asesorar = new ArrayList<>();

    public Alumno() {
    }

	
    public Alumno(int idAlumno, Usuario username) {
        this.idAlumno = idAlumno;
        this.username = username;
    }
    public Alumno(int idAlumno, Usuario username, List<Asesorar> asesorar) {
       this.idAlumno = idAlumno;
       this.username = username;
       this.asesorar = asesorar;
    }
   
    public int getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(int idAlumno) {
        this.idAlumno = idAlumno;
    }
    public Usuario getUsuario() {
        return this.username;
    }
    
    public void setUsuario(Usuario username) {
        this.username = username;
    }
    public List<Asesorar> getAsesorar() {
        return this.asesorar;
    }
    
    public void setAsesorar(List<Asesorar> asesorar) {
        this.asesorar = asesorar;
    }




}


