package modelo;
// Generated 2/10/2018 03:11:32 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * Asesorar generated by hbm2java
 */
@Entity
@Table(name = "Asesorar")
public class Asesorar  implements Serializable {

    @Id@GeneratedValue(strategy =GenerationType.IDENTITY )
    @Column(name = "idAsesorar")
     private int idAsesorar;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idAlumno")
     private Alumno idAlumno;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idHorario")
     private Horario idHorario;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idProfesor")
     private Profesor idProfesor;   
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idTema")
     private Tema idTema;

    public Asesorar() {
    }

    public Asesorar(int idAsesorar, Alumno idAlumno, Horario idHorario, Profesor idProfesor, Tema idTema) {
       this.idAsesorar = idAsesorar;
       this.idAlumno = idAlumno;
       this.idHorario = idHorario;
       this.idProfesor = idProfesor;
       this.idTema = idTema;
    }
   
    public int getAsesorar() {
        return this.idAsesorar;
    }
    
    public void setAsesorar(int idAsesorar) {
        this.idAsesorar = idAsesorar;
    }
    public Alumno getAlumno() {
        return this.idAlumno;
    }
    
    public void setAlumno(Alumno idAlumno) {
        this.idAlumno = idAlumno;
    }
    public Horario getHorario() {
        return this.idHorario;
    }
    
    public void setHorario(Horario idHorario) {
        this.idHorario = idHorario;
    }
    public Profesor getProfesor() {
        return this.idProfesor;
    }
    
    public void setProfesor(Profesor idProfesor) {
        this.idProfesor = idProfesor;
    }
    public Tema getTema() {
        return this.idTema;
    }
    
    public void setTema(Tema idTema) {
        this.idTema = idTema;
    }




}


