package modelo;
// Generated 2/10/2018 03:11:32 PM by Hibernate Tools 4.3.1



/**
 * Denuncia generated by hbm2java
 */
import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

@Entity
@Table(name = "Denuncia")
public class Denuncia  implements Serializable {

    @Id@GeneratedValue(strategy =GenerationType.IDENTITY )
    @Column(name = "idDenuncia")
     private int idDenuncia;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "username")
     private Usuario username;
    @Column(name = "motivo")     
     private String motivo;

    public Denuncia() {
    }

    public Denuncia(int idDenuncia, Usuario username, String motivo) {
       this.idDenuncia = idDenuncia;
       this.username = username;
       this.motivo = motivo;
    }
   
    public int getIdDenuncia() {
        return this.idDenuncia;
    }
    
    public void setIdDenuncia(int idDenuncia) {
        this.idDenuncia = idDenuncia;
    }
    public Usuario getUsuario() {
        return this.username;
    }
    
    public void setUsuario(Usuario username) {
        this.username = username;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }




}


