package modelo;
// Generated 2/10/2018 03:11:32 PM by Hibernate Tools 4.3.1
import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * Interesar generated by hbm2java
 */
@Entity
@Table(name = "Interesar")
public class Interesar  implements Serializable {

    @Id@GeneratedValue(strategy =GenerationType.IDENTITY )
    @Column(name = "idInteresar")
     private int idInteresar;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idMateria")
     private Materia idMateria;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idNivel")
     private Nivel idNivel;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idTema")
     private Tema idTema;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "username")
     private Usuario username;

    public Interesar() {
    }

    public Interesar(int idInteresar, Materia idMateria, Nivel idNivel, Tema idTema, Usuario username) {
       this.idInteresar = idInteresar;
       this.idMateria = idMateria;
       this.idNivel = idNivel;
       this.idTema = idTema;
       this.username = username;
    }
   
    public int getIdinteresar() {
        return this.idInteresar;
    }
    
    public void setIdinteresar(int idInteresar) {
        this.idInteresar = idInteresar;
    }
    public Materia getMateria() {
        return this.idMateria;
    }
    
    public void setMateria(Materia idMateria) {
        this.idMateria = idMateria;
    }
    public Nivel getNivel() {
        return this.idNivel;
    }
    
    public void setNivel(Nivel idNivel) {
        this.idNivel = idNivel;
    }
    public Tema getTema() {
        return this.idTema;
    }
    
    public void setTema(Tema idTema) {
        this.idTema = idTema;
    }
    public Usuario getUsuario() {
        return this.username;
    }
    
    public void setUsuario(Usuario username) {
        this.username = username;
    }




}


