package modelo;
// Generated 2/10/2018 03:11:32 PM by Hibernate Tools 4.3.1

import javax.persistence.OneToMany;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * Materia generated by hbm2java
 */
@Entity
@Table(name = "Materia")
public class Materia  implements Serializable {

    @Id@GeneratedValue(strategy =GenerationType.IDENTITY )
    @Column(name = "idMateria")
     private int idMateria;     
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idNivel")
     private Nivel idNivel;
    @Column(name = "materia")     
     private String materia;
    @OneToMany(mappedBy = "idMateria")
     private List<Interesar> interesar =new ArrayList<>();
    @OneToMany(mappedBy = "idMateria")    
     private List<Tema> tema =new ArrayList<>();

    public Materia() {
    }

	
    public Materia(int idMateria, Nivel idNivel, String materia) {
        this.idMateria = idMateria;
        this.idNivel = idNivel;
        this.materia = materia;
    }
    public Materia(int idMateria, Nivel idNivel, String materia, List<Interesar> interesar, List<Tema> tema) {
       this.idMateria = idMateria;
       this.idNivel = idNivel;
       this.materia = materia;
       this.interesar = interesar;
       this.tema = tema;
    }
   
    public int getIdMateria() {
        return this.idMateria;
    }
    
    public void setIdMateria(int idMateria) {
        this.idMateria = idMateria;
    }
    public Nivel getNivel() {
        return this.idNivel;
    }
    
    public void setNivel(Nivel idNivel) {
        this.idNivel = idNivel;
    }
    public String getMateria() {
        return this.materia;
    }
    
    public void setMateria(String materia) {
        this.materia = materia;
    }
    public List<Interesar> getInteresar() {
        return this.interesar;
    }
    
    public void setInteresar(List<Interesar> interesar) {
        this.interesar = interesar;
    }
    public List<Tema> getTema() {
        return this.tema;
    }
    
    public void setTema(List<Tema> tema) {
        this.tema = tema;
    }




}


