package modelo;
// Generated 2/10/2018 03:11:32 PM by Hibernate Tools 4.3.1

import javax.persistence.OneToMany;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * Profesor generated by hbm2java
 */
@Entity
@Table(name = "Profesor")
public class Profesor  implements Serializable {

    @Id@GeneratedValue(strategy =GenerationType.IDENTITY )
    @Column(name = "idProfesor")
     private int idProfesor;   
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "username")
     private Usuario username;
    @Column(name = "contratado")     
     private boolean contratado;
    @OneToMany(mappedBy = "idProfesor")    
     private List<Horario> horario =  new ArrayList<>();
    @OneToMany(mappedBy = "idProfesor")     
     private List<Asesorar> asesorar =  new ArrayList<>();

    public Profesor() {
    }

	
    public Profesor(int idProfesor, Usuario username, boolean contratado) {
        this.idProfesor = idProfesor;
        this.username = username;
        this.contratado = contratado;
    }
    public Profesor(int idProfesor, Usuario username, boolean contratado, List<Horario> horario, List<Asesorar> asesorar) {
       this.idProfesor = idProfesor;
       this.username = username;
       this.contratado = contratado;
       this.horario = horario;
       this.asesorar = asesorar;
    }
   
    public int getIdProfesor() {
        return this.idProfesor;
    }
    
    public void setIdProfesor(int idProfesor) {
        this.idProfesor = idProfesor;
    }
    public Usuario getUsuario() {
        return this.username;
    }
    
    public void setUsuario(Usuario username) {
        this.username = username;
    }
    public boolean getContratado() {
        return this.contratado;
    }
    
    public void setContratado(boolean contratado) {
        this.contratado = contratado;
    }
    public List<Horario> getHorario() {
        return this.horario;
    }
    
    public void setHorario(List<Horario> horario) {
        this.horario = horario;
    }
    public List<Asesorar> getAsesorar() {
        return this.asesorar;
    }
    
    public void setAsesorar(List<Asesorar> asesorar) {
        this.asesorar = asesorar;
    }




}


