package modelo;
// Generated 2/10/2018 03:11:32 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * Tarjeta generated by hbm2java
 */
@Entity
@Table(name = "Tarjeta")
public class Tarjeta  implements Serializable {

    @Id@GeneratedValue(strategy =GenerationType.IDENTITY )
    @Column(name = "idTarjeta")
     private int idTarjeta;     
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "username")
     private Usuario username;
    @Column(name = "ccv")     
     private int ccv;
    @Column(name = "numero")     
     private int numero;
    @Column(name = "vencimiento")     
     private Date vencimiento;

    public Tarjeta() {
    }

    public Tarjeta(int idTarjeta, Usuario username, int ccv, int numero, Date vencimiento) {
       this.idTarjeta = idTarjeta;
       this.username = username;
       this.ccv = ccv;
       this.numero = numero;
       this.vencimiento = vencimiento;
    }
   
    public int getIdTarjeta() {
        return this.idTarjeta;
    }
    
    public void setIdTarjeta(int idTarjeta) {
        this.idTarjeta = idTarjeta;
    }
    public Usuario getUsuario() {
        return this.username;
    }
    
    public void setUsuario(Usuario username) {
        this.username = username;
    }
    public int getCcv() {
        return this.ccv;
    }
    
    public void setCcv(int ccv) {
        this.ccv = ccv;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public Date getVencimiento() {
        return this.vencimiento;
    }
    
    public void setVencimiento(Date vencimiento) {
        this.vencimiento = vencimiento;
    }




}


