package modelo;
// Generated 2/10/2018 03:11:32 PM by Hibernate Tools 4.3.1


import javax.persistence.OneToMany;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * Tema generated by hbm2java
 */
@Entity
@Table(name = "Tema")
public class Tema  implements Serializable {

    @Id@GeneratedValue(strategy =GenerationType.IDENTITY )
    @Column(name = "idTema")
     private int idTema;     
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idMateria")
     private Materia idMateria;
    @Column(name = "tema")     
     private String tema;
    @OneToMany(mappedBy = "idTema")
     private List<Interesar> interesar = new ArrayList<>();
    @OneToMany(mappedBy = "idTema")
     private List<Asesorar> asesorar = new ArrayList<>();

    public Tema() {
    }

	
    public Tema(int idTema, Materia idMateria, String tema) {
        this.idTema = idTema;
        this.idMateria = idMateria;
        this.tema = tema;
    }
    public Tema(int idTema, Materia idMateria, String tema, List<Interesar> interesar, List<Asesorar> asesorar) {
       this.idTema = idTema;
       this.idMateria = idMateria;
       this.tema = tema;
       this.interesar = interesar;
       this.asesorar = asesorar;
    }
   
    public int getIdTema() {
        return this.idTema;
    }
    
    public void setIdTema(int idTema) {
        this.idTema = idTema;
    }
    public Materia getMateria() {
        return this.idMateria;
    }
    
    public void setMateria(Materia idMateria) {
        this.idMateria = idMateria;
    }
    public String getTema() {
        return this.tema;
    }
    
    public void setTema(String tema) {
        this.tema = tema;
    }
    public List<Interesar> getInteresar() {
        return this.interesar;
    }
    
    public void setInteresar(List<Interesar> interesar) {
        this.interesar = interesar;
    }
    public List<Asesorar> getAsesorar() {
        return this.asesorar;
    }
    
    public void setAsesorar(List<Asesorar> asesorar) {
        this.asesorar = asesorar;
    }




}


