package modelo;
// Generated 2/10/2018 03:11:32 PM by Hibernate Tools 4.3.1


import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import javax.annotation.Generated;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;


/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "Usuario")
public class Usuario  implements Serializable {


    @Id
    @Column(name = "username")
    private String username;
     @Column(name="correo")
     private String correo;
     @Column(name="nombre")
     private String nombre;
     @Column(name="direccion")
     private String direccion;
     @Column(name="fechaNacimiento")
     private Date fechaNacimiento;
     @GeneratedValue
     @Column(name="activo")
     private boolean activo;
     @Column(name="numero")
     private int numero;
     @GeneratedValue
     @Column(name="calificacion")
     private double calificacion;
     @Column(name="tipoUsuario")
     private String tipoUsuario;
     @Column(name="contrasena")
     private String contrasena;
     @OneToMany(mappedBy = "username")
     private List<Resena> resena = new ArrayList<>();
     @OneToMany(mappedBy = "username")
     private List<Denuncia> denuncia = new ArrayList<>();
     @OneToMany(mappedBy = "username")
     private List<Profesor> profesor = new ArrayList<>();
     @OneToMany(mappedBy = "username")
     private List<Alumno> alumno = new ArrayList<>();
     @OneToMany(mappedBy = "username")
     private List<Tarjeta> tarjeta = new ArrayList<>();
     @OneToMany(mappedBy = "username")
     private List <Interesar> interesar = new ArrayList<>();

    public Usuario() {
    }

	
    public Usuario(String username, String correo, String nombre, String direccion, Date fechaNacimiento, boolean activo, int numero, double calificacion, String tipoUsuario, String contrasena) {
        this.username = username;
        this.correo = correo;
        this.nombre = nombre;
        this.direccion = direccion;
        this.fechaNacimiento = fechaNacimiento;
        this.activo = activo;
        this.numero = numero;
        this.calificacion = calificacion;
        this.tipoUsuario = tipoUsuario;
        this.contrasena = contrasena;
    }
    public Usuario(String username, String correo, String nombre, String direccion, Date fechaNacimiento, boolean activo, int numero, double calificacion, String tipoUsuario, String contrasena, List<Resena> resena, List<Denuncia> denuncia, List<Profesor> profesor, List<Alumno> alumno, List<Tarjeta> tarjeta, List<Interesar> interesar) {
       this.username = username;
       this.correo = correo;
       this.nombre = nombre;
       this.direccion = direccion;
       this.fechaNacimiento = fechaNacimiento;
       this.activo = activo;
       this.numero = numero;
       this.calificacion = calificacion;
       this.tipoUsuario = tipoUsuario;
       this.contrasena = contrasena;
       this.resena = resena;
       this.denuncia = denuncia;
       this.profesor = profesor;
       this.alumno = alumno;
       this.tarjeta = tarjeta;
       this.interesar = interesar;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public double getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(double calificacion) {
        this.calificacion = calificacion;
    }
    public String getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(String tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public List<Resena> getResena() {
        return this.resena;
    }
    
    public void setResena(List<Resena> resena) {
        this.resena = resena;
    }
    public List<Denuncia> getDenuncia() {
        return this.denuncia;
    }
    
    public void setDenuncia(List<Denuncia> denuncia) {
        this.denuncia = denuncia;
    }
    public List<Profesor> getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(List<Profesor> profesor) {
        this.profesor = profesor;
    }
    public List<Alumno> getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(List<Alumno> alumno) {
        this.alumno = alumno;
    }
    public List<Tarjeta> getTarjeta() {
        return this.tarjeta;
    }
    
    public void setTarjeta(List<Tarjeta> tarjeta) {
        this.tarjeta = tarjeta;
    }
    public List<Interesar> getInteresar() {
        return this.interesar;
    }
    
    public void setInteresar(List<Interesar> interesar) {
        this.interesar = interesar;
    }




}


