package mx.unam.ciencias.is.sistemacolaborativo.mapeobd;
// Generated 21/10/2018 07:40:03 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Denuncia generated by hbm2java
 */
@Entity
@Table
public class Denuncia  implements java.io.Serializable {


    @Id@GeneratedValue(strategy =GenerationType.IDENTITY ) 
    @Column(name="iddenuncia")
     private int iddenuncia;
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_id_usuario")
     private Usuario fk_id_usuario;
    @Column(name="motivo")
     private String motivo;

    public Denuncia() {
    }

    public Denuncia(int iddenuncia, Usuario fk_id_usuario, String motivo) {
       this.iddenuncia = iddenuncia;
       this.fk_id_usuario = fk_id_usuario;
       this.motivo = motivo;
    }
   
    public int getIddenuncia() {
        return this.iddenuncia;
    }
    
    public void setIddenuncia(int iddenuncia) {
        this.iddenuncia = iddenuncia;
    }

    public Usuario getUsuario() {
        return this.fk_id_usuario;
    }
    
    public void setUsuario(Usuario fk_id_usuario) {
        this.fk_id_usuario = fk_id_usuario;
    }

    
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }

}


