/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.unam.ciencias.is.sistemacolaborativo.mapeobd;

import java.util.ArrayList;
import java.util.List;
import java.sql.Time;
import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
 * Horario generated by hbm2java
 */
@Entity
@Table(name = "Dia")
public class Dia  implements Serializable {

    @Id@GeneratedValue(strategy =GenerationType.IDENTITY )
    @Column(name = "iddia")
     private int iddia;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fk_id_profesor")        
     private Profesor fk_id_profesor;
    @Column(name = "dia")     
     private String dia;
    @OneToMany(mappedBy = "iddia")
    @LazyCollection(LazyCollectionOption.FALSE)    
     private List<Horario> horarios =  new ArrayList<>();

    public Dia() {
    }

    
    public Dia(int iddia, Profesor fk_id_profesor, String dia) {
        this.iddia = iddia;
        this.fk_id_profesor = fk_id_profesor;
        this.dia = dia;
    }

    public int getIddia() {
        return iddia;
    }

    public void setIddia(int iddia) {
        this.iddia = iddia;
    }

    public Profesor getFk_id_profesor() {
        return fk_id_profesor;
    }

    public void setFk_id_profesor(Profesor fk_id_profesor) {
        this.fk_id_profesor = fk_id_profesor;
    }

    public String getDia() {
        return dia;
    }

    public void setDia(String dia) {
        this.dia = dia;
    }

    public List<Horario> getHorarios() {
        return horarios;
    }

    public void setHorarios(List<Horario> horarios) {
        this.horarios = horarios;
    }








}


