package mx.unam.ciencias.is.sistemacolaborativo.mapeobd;
// Generated 21/10/2018 07:40:03 PM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
 * Nivel generated by hbm2java
 */
@Entity
@Table
public class Nivel  implements java.io.Serializable {

    @Id@GeneratedValue(strategy =GenerationType.IDENTITY ) 
    @Column(name="idnivel")
     private int idnivel;
    @Column(name="nivel")
     private String nivel;
    @OneToMany(mappedBy="idnivel")
    @LazyCollection(LazyCollectionOption.FALSE)     
     private List<Tema> temas = new ArrayList<>();
    @OneToMany(mappedBy="idnivel")
    @LazyCollection(LazyCollectionOption.FALSE)     
     private List<Nivelprofesor> nivelprofesors = new ArrayList<>();

    public Nivel() {
    }

	
    public Nivel(int idnivel, String nivel) {
        this.idnivel = idnivel;
        this.nivel = nivel;
    }
    public Nivel(int idnivel, String nivel, List<Tema> temas, List<Nivelprofesor> nivelprofesors) {
       this.idnivel = idnivel;
       this.nivel = nivel;
       this.temas = temas;
       this.nivelprofesors = nivelprofesors;
    }
   

    
    public int getIdnivel() {
        return this.idnivel;
    }
    
    public void setIdnivel(int idnivel) {
        this.idnivel = idnivel;
    }

    
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }

    public List<Tema> getTemas() {
        return temas;
    }

    public void setTemas(List<Tema> temas) {
        this.temas = temas;
    }

    public List<Nivelprofesor> getNivelprofesors() {
        return nivelprofesors;
    }

    public void setNivelprofesors(List<Nivelprofesor> nivelprofesors) {
        this.nivelprofesors = nivelprofesors;
    }






}


