package mx.unam.ciencias.is.sistemacolaborativo.mapeobd;
// Generated 21/10/2018 07:40:03 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
 * Nivelprofesor generated by hbm2java
 */
@Entity
@Table
public class Nivelprofesor  implements java.io.Serializable {


    @Id@GeneratedValue(strategy =GenerationType.IDENTITY ) 
    @Column(name="idnivelprofesor")
     private int idnivelprofesor;
    @ManyToOne()
    @LazyCollection(LazyCollectionOption.FALSE)    
    @JoinColumn(name="idnivel")
     private Nivel idnivel;
    @ManyToOne()
    @LazyCollection(LazyCollectionOption.FALSE)    
    @JoinColumn(name="fk_id_profesor")
     private Profesor fk_id_profesor;

    public Nivelprofesor() {
    }

    public Nivelprofesor(int idnivelprofesor, Nivel idnivel, Profesor fk_id_profesor) {
       this.idnivelprofesor = idnivelprofesor;
       this.idnivel = idnivel;
       this.fk_id_profesor = fk_id_profesor;
    }
   
    public int getIdnivelprofesor() {
        return this.idnivelprofesor;
    }
    
    public void setIdnivelprofesor(int idnivelprofesor) {
        this.idnivelprofesor = idnivelprofesor;
    }

    public Nivel getNivel() {
        return this.idnivel;
    }
    
    public void setNivel(Nivel idnivel) {
        this.idnivel = idnivel;
    }

    public Profesor getProfesor() {
        return this.fk_id_profesor;
    }
    
    public void setProfesor(Profesor fk_id_profesor) {
        this.fk_id_profesor = fk_id_profesor;
    }

}


