package mx.unam.ciencias.is.sistemacolaborativo.mapeobd;
// Generated 17/10/2018 11:33:19 AM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
 * Tema generated by hbm2java
 */
@Entity
@Table(name="tema")
public class Tema  implements java.io.Serializable {

    @Id@GeneratedValue(strategy =GenerationType.IDENTITY )     
    @Column(name="idtema" )
     private int idtema;
    @Column(name="tema")
     private String tema;
    @OneToMany(mappedBy="idtema")
    @LazyCollection(LazyCollectionOption.FALSE)    
     private List<Asesorar> asesorars = new ArrayList<>();
    @OneToMany(mappedBy="idtema")
    @LazyCollection(LazyCollectionOption.FALSE)    
     private List<Temaprofesor> temaprofesors = new ArrayList<>();
    @ManyToOne()
    @LazyCollection(LazyCollectionOption.FALSE)    
    @JoinColumn(name="idnivel")
     private Nivel idnivel;     

    public Tema() {
    }

	
    public Tema(int idtema, String tema) {
        this.idtema = idtema;
        this.tema = tema;
    }
    public Tema(int idtema, String tema, List<Asesorar> asesorars, List<Temaprofesor> temaprofesors) {
       this.idtema = idtema;
       this.tema = tema;
       this.asesorars = asesorars;
       this.temaprofesors = temaprofesors;
    }
   
    
    public int getIdtema() {
        return this.idtema;
    }
    
    public void setIdtema(int idtema) {
        this.idtema = idtema;
    }

    
    public String getTema() {
        return this.tema;
    }
    
    public void setTema(String tema) {
        this.tema = tema;
    }

    public List<Asesorar> getAsesorars() {
        return this.asesorars;
    }
    
    public void setAsesorars(List<Asesorar> asesorars) {
        this.asesorars = asesorars;
    }

    public List<Temaprofesor> getTemaprofesors() {
        return this.temaprofesors;
    }
    
    public void setTemaprofesors(List<Temaprofesor> temaprofesors) {
        this.temaprofesors = temaprofesors;
    }

    public Nivel getIdnivel() {
        return idnivel;
    }

    public void setIdnivel(Nivel idnivel) {
        this.idnivel = idnivel;
    }




}


