package mx.unam.ciencias.is.sistemacolaborativo.mapeobd;
// Generated 17/10/2018 11:33:19 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
 * Temaprofesor generated by hbm2java
 */
@Entity
@Table(name="temaprofesor")
public class Temaprofesor  implements java.io.Serializable {


    @Id@GeneratedValue(strategy =GenerationType.IDENTITY ) 
    @Column(name="idtemaprofesor")
     private int idtemaprofesor;
    @ManyToOne()
    @LazyCollection(LazyCollectionOption.FALSE) 
    @JoinColumn(name="fk_id_profesor")
     private Profesor fk_id_profesor;
    @ManyToOne()
    @LazyCollection(LazyCollectionOption.FALSE)    
    @JoinColumn(name="idtema")
     private Tema idtema;

    public Temaprofesor() {
    }

    public Temaprofesor(int idtemaprofesor, Profesor fk_id_profesor, Tema idtema) {
       this.idtemaprofesor = idtemaprofesor;
       this.fk_id_profesor = fk_id_profesor;
       this.idtema = idtema;
    }
   
    public int getIdtemaprofesor() {
        return this.idtemaprofesor;
    }
    
    public void setIdtemaprofesor(int idtemaprofesor) {
        this.idtemaprofesor = idtemaprofesor;
    }

    public Profesor getProfesor() {
        return this.fk_id_profesor;
    }
    
    public void setProfesor(Profesor fk_id_profesor) {
        this.fk_id_profesor = fk_id_profesor;
    }

    public Tema getTema() {
        return this.idtema;
    }
    
    public void setTema(Tema idtema) {
        this.idtema = idtema;
    }




}


